name: Foxy CI

on:
  schedule:
    - cron: "0 4 1-7 * 1"
    # First monday of the month, at 4am
  push:
    branches: [ foxy ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up GNAT toolchain
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: fsf

    - name: Set up ROS2
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: foxy

    - name: Add additional required packages
      run: sudo apt update && sudo apt install ros-foxy-test-msgs

    - name: Build
      run: >
        source /opt/ros/foxy/setup.bash && 
        colcon build --event-handlers console_direct+ --executor sequential

    - name: Run tests
      run: >
        ls -al install &&
        source ${{ github.workspace }}/install/setup.sh &&
        ros2 run rclada rclada_selftest_dynamic &&
        ros2 run rclada rclada_selftest_static &&
        ros2 run rclada rclada_test_allocators 4
