name: LTS CI

on:
  schedule:
    - cron: "0 4 1-7 * 1"
    # First monday of the month, at 4am
  push:
    branches: [ jazzy, lts ]
  pull_request:
  workflow_dispatch: # Manually triggered:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        v:
          - os: ubuntu-24.04
            ros: jazzy

    runs-on: ${{ matrix.v.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up GNAT toolchain
      shell: bash
      run: >
        sudo apt update
        && sudo apt install -y gprbuild gnat

    - name: Set up ROS2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.v.ros }}

    - name: Add additional required packages
      run: |
        cat ros2deps.txt | tr '_' '-' | while read dep; do
          sudo apt-get install -y ros-${{ matrix.v.ros }}-$dep
        done

    - name: Build
      run: >
        source /opt/ros/${{ matrix.v.ros }}/setup.bash
        && colcon build --event-handlers console_direct+ --executor sequential

    - name: Run tests
      run: >
        ls -al install
        && source ${{ github.workspace }}/install/setup.sh
        && ros2 run rclada rclada_selftest_dynamic
        && ros2 run rclada rclada_selftest_static
      #  && ros2 run rclada rclada_test_allocators 4
      # TODO: find out why this test is failing
